language: android
android:
  components:
    - build-tools-27.0.2
    - android-27
    - tools
    - platform-tools
    - tools
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'