language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools

    - build-tools-27.0.2
    - android-27
    - tools

    - extra-google-m2repository
    - extra-android-support

  licenses:
    - 'android-sdk-license-.+'
    - '.+'

notifications:
  email: false
