language: android
jdk: oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-26"

android:
  components:
    - tools
    - tools
    - platform-tools

    - build-tools-27.0.2
    - android-27
    - tools
    - add-on

    - extra-google-m2repository
    - extra-android-support

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'

script:
  # By default Travis-ci executes './gradlew build connectedCheck' if no 'script:' section found.
  - ./gradlew build


notifications:
  email: false
